### ISSUE TITLE
Machine learning roadmap

### ISSUE THREAD

**Issue by engelsmann** [engelsmann/bedom#15]
Hvilken vej skal vi i bedom-projektet mht. brug af machine learning?

**Comment by engelsmann** [comment]
**Klassificering** (*classification*): Eventuelt. Kan være læringsstile eller andre læringsmæssige typer/profiler, som eleverne matches imod.
**Anomalidetektering** (*anomaly detection*): Til at fange svage elever (hvis de falder udenfor normen) og spotte de stærke.
**Sammenklyngning** (*clustering*):
**Regression**: Relation mellem numeriske data, fx ml *pdes.* antal svar, antal korrekte svar, gennemsnitlig hjælpe-adfærds-score og *pdas.* linear score/standpunktskarakter.

**Comment by engelsmann** [comment]
Til inspiration kan [denne videoserie](https://github.com/mpfrush/Python-Scikit-Learn-Exercises) måske hjælpe. Ja, her på GitHub ligger de Jupyter Notebooks, som Kevin Markham bruger i sine videoer, så først hopper man til et andet GitHub-*repository*, og derfra kan man (downloade notebooks og) gå videre til Youtube.

**Comment by engelsmann** [comment]
Det vil være interessant **efter MVP-stadiet** at implementere med [Ensemble learning](https://en.wikipedia.org/wiki/Ensemble_learning) hvor det kan forbedre modelprædiktionerne betragteligt.

**Comment by engelsmann** [comment]
**Sentiment analysis**, [PLM3ch8](https://bookshelf.vitalsource.com/#/books/9781789958294/cfi/6/24!/4/2/4/2@0:0): Gruppering af genrer ud fra **ord** der står alene, og **sekvenser af ord**. [Stemming](http://snowball.tartarus.org/algorithms/danish/stemmer.html),

**Comment by engelsmann** [comment]
### Hurtig feedback på korte spørgsmål om emnet
På linje med [skriftlige afleveringer, se kommentar](https://github.com/engelsmann/bedom/issues/13#issuecomment-717090060) - kunne man så have en ord-sæk, [bag-of-words](https://machinelearningmastery.com/gentle-introduction-bag-words-model/), som indikerer et SOLO-niveau?

- [ ] Sæt med ord-sække knyttes til hvert forløb (HOT SOLO-tankekort, evt. dublerede kort. Ikke blot de fire niveauer).
- [ ] I sækken er ikke kun behov for ord, men også for idiomer/fraser/kilchéer knyttet til hver tankekort-opgave.
- [ ] Spørgsmålene stilles løbende gennem forløbet. 
- [ ] Svar knyttes til eleven og til forløbet.
- [ ] Feedback til eleven valideres (i afprøvningsfase) af læreren inden den sendes til eleven. Sendes inden næste time begynder.
- [ ] Skift mellem sæt-af-ordsække ( = forløbs-emner) i repetitionsfasen
